name: Benchmark

on:
  push:
    branches: [master]

jobs:
  benchmark-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run JVM benchmark
        run: ./gradlew :jsonpath-benchmarks:jvmRun

      - name: Run Node JS benchmark
        run: ./gradlew :jsonpath-benchmarks:jsNodeProductionRun

      - name: Run Native Linux benchmark
        run: ./gradlew :jsonpath-benchmarks:runReleaseExecutableLinuxX64

  benchmark-mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run Native Mac X64 benchmark
        run: ./gradlew :jsonpath-benchmarks:runReleaseExecutableMacosX64

      - name: Run Native Mac ARM64 benchmark
        run: ./gradlew :jsonpath-benchmarks:runReleaseExecutableMacosArm64

  benchmark-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run Native Mingw benchmark
        run: ./gradlew :jsonpath-benchmarks:runReleaseExecutableMingwX64
