name: Check

on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.2.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - uses: gradle/wrapper-validation-action@v2.1.1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true

      - name: Run gradle check
        run: ./gradlew check

      - name: Run ktlint and detekt
        run: ./format --no-format && ./gradlew detektAppleMain detektJvmMain detektJsMain detektMetadataMain
